# Generated by Django 2.1.10 on 2019-07-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleKeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Account')),
                ('login_name', models.CharField(max_length=100, verbose_name='Login Name')),
                ('login_password', models.CharField(max_length=100, verbose_name='Login Password')),
                ('token', models.TextField(blank=True, default=None, null=True, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Google Keep',
                'verbose_name_plural': 'Google Keep',
            },
        ),
    ]
