# Generated by Django 2.0.6 on 2018-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
