# Generated by Django 2.0.6 on 2018-06-21 02:24

from django.db import migrations
# import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        # ('taggit', '0002_auto_20150616_2121'),
        ('histories', '0003_auto_20180619_1811'),
    ]

    operations = [
#         migrations.AddField(
#             model_name='link',
#             name='tags',
#             field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
#         ),
    ]
