# Generated by Django 2.0.6 on 2018-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0005_auto_20180624_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
