# Generated by Django 2.0.6 on 2018-06-30 01:43

from django.db import migrations, models
import django.db.models.deletion
import histories.models.methods


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0006_domain_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('text', models.TextField()),
            ],
            bases=(models.Model, histories.models.methods.Note),
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='visited_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notelink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histories.Link'),
        ),
        migrations.AddField(
            model_name='notelink',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histories.Note'),
        ),
    ]
