# Generated by Django 2.0.6 on 2018-07-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0007_auto_20180630_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notelink',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='notelink',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
