# Generated by Django 2.2.2 on 2019-07-08 03:13

from django.db import migrations
import mytaggit.models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0009_auto_20180703_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=mytaggit.models.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mytaggit.TaggedItem', to='mytaggit.Tag', verbose_name='Tags'),
        ),
    ]
