# Generated by Django 2.2.4 on 2019-09-07 08:41

from django.db import migrations
import mytaggit.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaggit', '0004_auto_20181009_1248'),
        ('histories', '0010_auto_20190708_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=mytaggit.models.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='HistoryLink', through='mytaggit.TaggedItem', to='mytaggit.Tag', verbose_name='Tags'),
        ),
    ]
